trigger: none
pr: none

pool:
  name: Default

variables:

  # ---------------------------------------
  # Azure Service Connection
  # ---------------------------------------
  azureServiceConnection: 'my-azure-connection'

  # ---------------------------------------
  # Terraform Remote Backend
  # ---------------------------------------
  backendResourceGroup: 'tfstate-rg'
  backendStorageAccount: 'ecomtfstate001'
  backendContainer: 'tfstate'
  backendKey: 'ecom-dev-terraform.tfstate'

  acrName: 'ecomacrdev001'
  acrLoginServer: 'ecomacrdev001.azurecr.io'

  # ---------------------------------------
  # ACR & AKS Connections (Future Stages)
  # ---------------------------------------
  acrServiceConnection: 'my-azure-connection'
  aksServiceConnection: 'my-azure-connection'

  # ---------------------------------------
  # ACR Login Server
  # ---------------------------------------
  # acrHost: 'ecomacrdev001.azurecr.io'

stages:

# =======================================
# STAGE 1: TERRAFORM INFRASTRUCTURE
# =======================================
- stage: Infrastructure
  displayName: 'Step 1: Deploy Azure Infrastructure'

  jobs:
  - job: Terraform
    displayName: 'Terraform Deployment'

    steps:

    # Install Terraform
    - task: TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest'

    # Terraform Format Check
    - script: terraform fmt -check
      displayName: 'Terraform Format Check'
      workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure'

    # Terraform Init
    - task: TerraformTaskV2@2
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure'
        backendServiceArm: '$(azureServiceConnection)'
        backendAzureRmResourceGroupName: '$(backendResourceGroup)'
        backendAzureRmStorageAccountName: '$(backendStorageAccount)'
        backendAzureRmContainerName: '$(backendContainer)'
        backendAzureRmKey: '$(backendKey)'

    # Terraform Validate
    - script: terraform validate
      displayName: 'Terraform Validate'
      workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure'

    # Terraform Plan
    - task: TerraformTaskV2@2
      displayName: 'Terraform Plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure'
        commandOptions: '-var-file="terraform.tfvars"'
        environmentServiceNameAzureRM: '$(azureServiceConnection)'

    # Terraform Apply
    - task: TerraformTaskV2@2
      displayName: 'Terraform Apply'
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure'
        commandOptions: '-var-file="terraform.tfvars" -auto-approve'
        environmentServiceNameAzureRM: '$(azureServiceConnection)'


      


# ===================================
# STAGE 2 - BUILD & PUSH DOCKER
# ===================================
- stage: Build
  displayName: Build & Push Docker Images
  dependsOn: Infrastructure

  jobs:
  - job: BuildAndPush
    displayName: Build Containers

    steps:

    - task: AzureCLI@2
      displayName: Login to ACR
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name $(acrName)

    - script: |
        docker build -t $(acrLoginServer)/frontend:latest src/frontend
        docker push $(acrLoginServer)/frontend:latest
      displayName: Build & Push Frontend

    - script: |
        docker build -t $(acrLoginServer)/user-api:latest src/user-api
        docker push $(acrLoginServer)/user-api:latest
      displayName: Build & Push User API

    - script: |
        docker build -t $(acrLoginServer)/product-api:latest src/product-api
        docker push $(acrLoginServer)/product-api:latest
      displayName: Build & Push Product API

    - script: |
        docker build -t $(acrLoginServer)/order-api:latest src/order-api
        docker push $(acrLoginServer)/order-api:latest
      displayName: Build & Push Order API


# ===================================
# STAGE 3 - DEPLOY TO AKS
# ===================================
- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: Build

  jobs:
  - job: KubernetesDeploy
    displayName: Deploy Kubernetes Manifests

    steps:

    - task: AzureCLI@2
      displayName: Connect to AKS
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          az aks get-credentials --resource-group ecom-rg-dev-canadacentral --name ecom-aks-cluster-dev-001 --overwrite-existing

    - script: |
        kubectl apply -f kube/
      displayName: Deploy Kubernetes Manifests
