parameters:
- name: environment
  displayName: Select Environment
  type: string
  default: dev
  values:
  - dev
  - qa
  - uat

trigger:
- main

pool:
  name: Default

variables:

  azureServiceConnection: 'my-azure-connection'
  environment: ${{ parameters.environment }}
  acrName: 'ecomacr$(environment)001'
  acrLoginServer: 'ecomacr$(environment)001.azurecr.io'

stages:

- stage: Build
  displayName: Build & Push Docker Images

  jobs:
  - job: DockerBuild

    steps:

    - task: AzureCLI@2
      displayName: Login to ACR
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name $(acrName)

    - script: |
        docker buildx create --use || true
        docker buildx build --platform linux/arm64 -t $(acrLoginServer)/frontend:latest src/frontend --push
      displayName: Build & Push Frontend

    - script: |
        docker buildx build --platform linux/arm64 -t $(acrLoginServer)/user-api:latest src/user-api --push
      displayName: Build & Push User API

    - script: |
        docker buildx build --platform linux/arm64 -t $(acrLoginServer)/product-api:latest src/product-api --push
      displayName: Build & Push Product API

    - script: |
        docker buildx build --platform linux/arm64 -t $(acrLoginServer)/order-api:latest src/order-api --push
      displayName: Build & Push Order API