parameters:
- name: environment
  displayName: Select Environment
  type: string
  default: dev
  values:
  - dev
  - qa
  - uat

trigger: none

pool:
  name: Default

variables:

  environment: ${{ parameters.environment }}
  azureServiceConnection: 'my-azure-connection'

stages:

- stage: Deploy
  displayName: Deploy to AKS

  jobs:
  - job: KubernetesDeployment

    steps:

    - task: AzureCLI@2
      displayName: Connect to AKS
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          az aks get-credentials --resource-group ecom-rg-$(environment)-canadacentral --name ecom-aks-cluster-$(environment)-001 --overwrite-existing

    - script: |
        kubectl apply -f kube/
      displayName: Deploy Kubernetes Manifests

    - script: |
        kubectl get pods
        kubectl get svc
      displayName: Verify Deployment