trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/frontend/*

pool: Default

parameters:
- name: ENVIRONMENT
  displayName: "Target Environment"
  type: string
  default: dev
  values:
  - dev
  - qa
  - uat
  - prod
-   name: PROMOTE_IMAGE_TAG
  displayName: "Select Dev Image Tag (Ex: frontend-eeb66bf1)"
  type: string
  default: ''

variables:
  azureServiceConnection: 'sc-ecom-azure-001' # Replace with your Azure DevOps Service Connection name
  imageTag: 'v$(Build.BuildId)'
  imageName: 'frontend'
  COMMIT_ID: $[ substring(variables['Build.SourceVersion'],0,8) ]
  IMAGE_TAG: $(imageName)-$(COMMIT_ID)

stages:

# ==========================================
# STAGE 1: BUILD & PUSH (DEV)
# ==========================================
- stage: BuildDev
  displayName: 'Build & Push $(imageName)'
  condition: eq('${{ parameters.ENVIRONMENT }}', 'dev')
  jobs:
  - job: DockerBuild
    steps:
    - task: AzureCLI@2
      displayName: Login to ACR
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name ecomacrdev001

    - script: |
        docker buildx create --use || true
        docker buildx build --platform linux/arm64 -t ecomacrdev001.azurecr.io/$(imageName):$(IMAGE_TAG) src/$(imageName) --push
      displayName: Build & Push Docker Image

# ==========================================
# STAGE 2: DEPLOY TO AKS (DEV)
# ==========================================
- stage: DeployDev
  displayName: Deploy $(imageName) to AKS DEV
  dependsOn: BuildDev
  condition: eq('${{ parameters.ENVIRONMENT }}', 'dev')
  jobs:
  - job: KubernetesDeployment
    steps:
    - task: AzureCLI@2
      displayName: Connect to AKS DEV
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          az aks get-credentials --resource-group ecom-rg-dev-canadacentral --name ecom-aks-cluster-dev-001 --overwrite-existing

    - script: |
        kubectl apply -f kube/$(imageName).yaml
      displayName: Deploy Kubernetes Manifest

    - script: |
        kubectl set image deployment/$(imageName) $(imageName)=ecomacrdev001.azurecr.io/$(imageName):$(IMAGE_TAG)
      displayName: Update Image in Deployment

    - script: |
        kubectl rollout restart deployment $(imageName)
      displayName: Force Rollout Restart for Deployment

    - script: |
        kubectl get pods -l app=$(imageName)
        kubectl get svc $(imageName)-service
      displayName: Verify Deployment

# ==========================================
# STAGE 3: PROMOTE (PULL, TAG, PUSH) & DEPLOY TO QA
- stage: DeployQA
  dependsOn: [] 
  condition: eq('${{ parameters.ENVIRONMENT }}', 'qa')
  jobs:
  - job: PromoteAndDeploy
    steps:
    - task: AzureCLI@2
      displayName: 'QA Promotion and Kubernetes Deployment'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: ps
        inlineScript: |

          $t = "${{ parameters.PROMOTE_IMAGE_TAG }}"
          if (-not $t) { $t = "$(IMAGE_TAG)" }

          Write-Host "------------------------------------------------"
          Write-Host "STEP 1: PROMOTING IMAGE FROM DEV TO QA ACR"
          Write-Host "------------------------------------------------"
          az acr login --name ecomacrdev001
          az acr login --name ecomacrqa001
          Write-Host "Promoting Tag: $t"
          docker pull ecomacrdev001.azurecr.io/$(imageName):$t
          docker tag  ecomacrdev001.azurecr.io/$(imageName):$t ecomacrqa001.azurecr.io/$(imageName):$t
          docker push ecomacrqa001.azurecr.io/$(imageName):$t

          Write-Host "------------------------------------------------"
          Write-Host "STEP 2: CONNECTING TO AKS AND DEPLOYING"
          Write-Host "------------------------------------------------"
          az aks get-credentials --resource-group ecom-rg-qa-canadacentral --name ecom-aks-cluster-qa-001 --overwrite-existing
          

          kubectl apply -f kube/$(imageName).yaml
          

          kubectl set image deployment/$(imageName) $(imageName)=ecomacrqa001.azurecr.io/$(imageName):$t
          kubectl rollout restart deployment $(imageName)

          Write-Host "------------------------------------------------"
          Write-Host "STEP 3: VERIFYING DEPLOYMENT"
          Write-Host "------------------------------------------------"
          kubectl get pods -l app=$(imageName)
          kubectl get svc $(imageName)-service
          Write-Host "QA Deployment Completed Successfully!"


# ==========================================
# STAGE 4: PROMOTE (PULL, TAG, PUSH) & DEPLOY TO UAT
# ==========================================
- stage: DeployUAT
  dependsOn: [] 
  condition: eq('${{ parameters.ENVIRONMENT }}', 'uat')
  jobs:
  - job: PromoteAndDeploy
    steps:
    - task: AzureCLI@2
      displayName: 'Promote from QA to UAT ACR'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          $tag = "${{ parameters.PROMOTE_IMAGE_TAG }}"
          if (-not $tag) { $tag = "$(IMAGE_TAG)" }
          
          az acr login --name ecomacrdev001
          az acr login --name ecomacrqa001
          
          docker pull ecomacrdev001.azurecr.io/$(imageName):$tag
          docker tag  ecomacrdev001.azurecr.io/$(imageName):$tag ecomacrqa001.azurecr.io/$(imageName):$tag
          docker push ecomacrqa001.azurecr.io/$(imageName):$tag
          
        inlineScript: |
          az acr login --name ecomacrqa001
          az acr login --name ecomacruat001
          docker pull ecomacrqa001.azurecr.io/$(imageName):$(imageTag)
          docker tag  ecomacrqa001.azurecr.io/$(imageName):$(imageTag) ecomacruat001.azurecr.io/$(imageName):$(IMAGE_TAG)
          docker push ecomacruat001.azurecr.io/$(imageName):$(IMAGE_TAG)

    - task: AzureCLI@2
      displayName: Connect to AKS UAT
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          az aks get-credentials --resource-group ecom-rg-uat-canadacentral --name ecom-aks-cluster-uat-001 --overwrite-existing
          
    - script: |
        kubectl apply -f kube/$(imageName).yaml
      displayName: Deploy Kubernetes Manifest to UAT

    - script: |
        kubectl set image deployment/$(imageName) $(imageName)=ecomacruat001.azurecr.io/$(imageName):$(IMAGE_TAG)
      displayName: Update Image in UAT Deployment

    - script: |
        kubectl rollout restart deployment $(imageName)
      displayName: Force Rollout Restart for UAT Deployment

    - script: |
        kubectl get pods -l app=$(imageName)
        kubectl get svc $(imageName)-service
      displayName: Verify UAT Deployment

# ==========================================
# STAGE 5: PROD APPROVAL
# ==========================================
- stage: ApproveProd
  dependsOn: []
  condition: eq('${{ parameters.ENVIRONMENT }}', 'prod')
  jobs:
  - job: ManualApproval
    pool: server
    steps:
    - task: ManualValidation@0
      inputs:
        notifyUsers: ''
        instructions: 'Approve to Push $(imageName) image to PROD ACR and Deploy to AKS PROD cluster'
        onTimeout: 'reject'

# ==========================================
# STAGE 6: PROMOTE (PULL, TAG, PUSH) & DEPLOY TO PROD
# ==========================================
- stage: DeployProd
  dependsOn: ApproveProd
  condition: eq('${{ parameters.ENVIRONMENT }}', 'prod')
  jobs:
  - job: PromoteAndDeployProd
    steps:
    - task: AzureCLI@2
      displayName: 'Promote from UAT to PROD ACR'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name ecomacruat001
          az acr login --name ecomacrprod001
          docker pull ecomacruat001.azurecr.io/$(imageName):$(imageTag)
          docker tag  ecomacruat001.azurecr.io/$(imageName):$(imageTag) ecomacrprod001.azurecr.io/$(imageName):$(IMAGE_TAG)
          docker push ecomacrprod001.azurecr.io/$(imageName):$(IMAGE_TAG)

    - task: AzureCLI@2
      displayName: Connect to AKS PROD
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          az aks get-credentials --resource-group ecom-rg-prod-canadacentral --name ecom-aks-cluster-prod-001 --overwrite-existing

    - script: |
        kubectl apply -f kube/$(imageName).yaml
      displayName: Deploy Kubernetes Manifest to PROD

    - script: |
        kubectl set image deployment/$(imageName) $(imageName)=ecomacrprod001.azurecr.io/$(imageName):$(IMAGE_TAG)
      displayName: Update Image in PROD Deployment

    - script: |
        kubectl rollout restart deployment $(imageName)
      displayName: Force Rollout Restart for PROD Deployment

    - script: |
        kubectl get pods -l app=$(imageName)
        kubectl get svc $(imageName)-service
      displayName: Verify PROD Deployment
