parameters:
- name: environment
  displayName: Select Environment
  type: string
  default: dev
  values:
  - dev
  - qa
  - uat
- name: action
  displayName: Select Action
  type: string
  default: Apply
  values:
  - Apply
  - Destroy

trigger: none
pr: none

pool:
  name: Default

variables:
  environment: ${{ parameters.environment }}
  action: ${{ parameters.action }}
  azureServiceConnection: 'sc-ecom-azure-001'

stages:
- stage: Terraform
  displayName: 'Terraform ${{ parameters.action }} - ${{ parameters.environment }}'
  jobs:
  - job: TerraformDeployment
    steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: latest
        
    - task: AzureCLI@2
      displayName: 'Terraform Format Check'
      inputs:
        azureSubscription: '$(azureServiceConnection)'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd infrastructure
          terraform fmt -check

    - task: AzureCLI@2
      displayName: 'Terraform Init'
      inputs:
        azureSubscription: '$(azureServiceConnection)'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd infrastructure
          terraform init -backend-config="environments/primary_canada_central/backend_configs/$(environment)-backend.conf"

    - task: AzureCLI@2
      displayName: 'Terraform Validate'
      inputs:
        azureSubscription: '$(azureServiceConnection)'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd infrastructure
          terraform validate

    - task: AzureCLI@2
      displayName: 'Terraform Plan'
      inputs:
        azureSubscription: '$(azureServiceConnection)'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd infrastructure
          if ('${{ parameters.action }}' -eq 'Destroy') {
            terraform plan -destroy -var-file="environments/primary_canada_central/tfvars/$(environment).tfvars" -out=tfplan
          } else {
            terraform plan -var-file="environments/primary_canada_central/tfvars/$(environment).tfvars" -out=tfplan
          }

    - task: AzureCLI@2
      displayName: 'Terraform Apply'
      condition: eq('${{ parameters.action }}', 'Apply')
      inputs:
        azureSubscription: '$(azureServiceConnection)'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd infrastructure
          terraform apply -auto-approve tfplan

    - task: AzureCLI@2
      displayName: 'Terraform Destroy'
      condition: eq('${{ parameters.action }}', 'Destroy')
      inputs:
        azureSubscription: '$(azureServiceConnection)'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd infrastructure
          terraform apply -auto-approve tfplan