parameters:
- name: environment
  displayName: Select Environment
  type: string
  default: dev
  values:
  - dev
  - qa
  - uat

trigger: none
pr: none

pool:
  name: Default

variables:
  environment: ${{ parameters.environment }}
  azureServiceConnection: 'sc-ecom-azure-001'
  backendKey: 'ecom-$(environment)-terraform.tfstate'

stages:
- stage: Terraform
  displayName: Deploy Infrastructure
  jobs:
  - job: TerraformDeployment
    steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: latest
    - script: terraform fmt -check
      displayName: Terraform Format Check
      workingDirectory: infrastructure
      
    - task: TerraformTaskV2@2
      displayName: Terraform Init
      inputs:
        provider: azurerm
        command: init
        workingDirectory: infrastructure
        backendServiceArm: $(azureServiceConnection)
        backendAzureRmResourceGroupName: $(backendResourceGroup)
        backendAzureRmStorageAccountName: $(backendStorageAccount)
        backendAzureRmContainerName: $(backendContainer)
        backendAzureRmKey: $(backendKey)

    - script: terraform validate
      displayName: Terraform Validate
      workingDirectory: infrastructure

    - task: TerraformTaskV2@2
      displayName: Terraform Plan
      inputs:
        provider: azurerm
        command: plan
        workingDirectory: infrastructure

        commandOptions: '-var-file="environments/primary_canada_central/tfvars/$(environment).tfvars"'
        environmentServiceNameAzureRM: $(azureServiceConnection)

    - task: TerraformTaskV2@2
      displayName: Terraform Apply
      inputs:
        provider: azurerm
        command: apply
        workingDirectory: infrastructure
        commandOptions: '-var-file="environments/primary_canada_central/tfvars/$(environment).tfvars"'
        environmentServiceNameAzureRM: $(azureServiceConnection)