trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/product-api/*

pool: Default

parameters:
- name: ENVIRONMENT
  displayName: "Target Environment"
  type: string
  default: dev
  values:
  - dev
  - qa
  - uat
  - prod
- name: PROMOTE_IMAGE_TAG
  displayName: "Select Dev Image Tag (Ex: product-api-eeb66bf1)"
  type: string
  default: ''

variables:
  azureServiceConnection: 'sc-ecom-azure-001'
  serviceName: 'product-api'
  COMMIT_ID: $[ substring(variables['Build.SourceVersion'],0,8) ]
  IMAGE_TAG: $(serviceName)-$(COMMIT_ID)
  kube_manifest_path: 'kube/product-service'

stages:

# ==========================================
# STAGE 1: BUILD & PUSH (DEV)
# ==========================================
- stage: BuildDev
  displayName: 'Build & Push $(serviceName)'
  condition: eq('${{ parameters.ENVIRONMENT }}', 'dev')
  jobs:
  - job: DockerBuild
    steps:
    - task: AzureCLI@2
      displayName: Login to ACR
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name ecomacrdev001

    - script: |
        docker buildx create --use || true
        docker buildx build --platform linux/arm64 -t ecomacrdev001.azurecr.io/$(serviceName):$(IMAGE_TAG) src/$(serviceName) --push
      displayName: Build & Push Docker Image

# ==========================================
# STAGE 2: DEPLOY TO AKS (DEV)
# ==========================================
- stage: DeployDev
  displayName: Deploy $(serviceName) to AKS DEV
  dependsOn: BuildDev
  condition: eq('${{ parameters.ENVIRONMENT }}', 'dev')
  jobs:
  - job: KubernetesDeployment
    steps:
    - task: AzureCLI@2
      displayName: Connect to AKS DEV
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          az aks get-credentials --resource-group ecom-rg-dev-canadacentral --name ecom-aks-cluster-dev-001 --overwrite-existing
          $ns = "${{ parameters.ENVIRONMENT }}"
          $nsExists = kubectl get namespace $ns --ignore-not-found
          if (-not $nsExists) { kubectl create namespace $ns }

    - task: PowerShell@2
      displayName: Replace Domain in Ingress and Deploy
      inputs:
        targetType: 'inline'
        script: |
          $envName = "${{ parameters.ENVIRONMENT }}"
          $domainName = "ecom-store-vd.duckdns.org"
          if ($envName -eq "dev") {
            $domainName = "ecom-dev-vd.duckdns.org"
          } elseif ($envName -eq "qa") {
            $domainName = "ecom-qa-vd.duckdns.org"
          }
          
          Write-Host "Replacing domains in $(kube_manifest_path) with $domainName"
          Get-ChildItem -Path $(kube_manifest_path) -Filter *ingress.yaml | ForEach-Object {
            (Get-Content $_.FullName) -replace 'ecom-store-vd.duckdns.org', $domainName | Set-Content $_.FullName
          }

    - script: |
        kubectl apply -f $(kube_manifest_path) -n ${{ parameters.ENVIRONMENT }}
        kubectl set image deployment/$(serviceName) $(serviceName)=ecomacrdev001.azurecr.io/$(serviceName):$(IMAGE_TAG) -n ${{ parameters.ENVIRONMENT }}
        kubectl rollout restart deployment $(serviceName) -n ${{ parameters.ENVIRONMENT }}
      displayName: Deploy & Update Image

    - script: |
        kubectl get pods -l app=$(serviceName) -n ${{ parameters.ENVIRONMENT }}
        kubectl get svc $(serviceName)-service -n ${{ parameters.ENVIRONMENT }}
      displayName: Verify Deployment

# ==========================================
# STAGE 3: PROMOTE & DEPLOY TO QA
# ==========================================
- stage: DeployQA
  dependsOn: [] 
  condition: eq('${{ parameters.ENVIRONMENT }}', 'qa')
  jobs:
  - job: PromoteAndDeploy
    steps:
    - template: templates/promote-deploy.yml
      parameters:
        environment: qa
        sourceAcr: ecomacrdev001
        targetAcr: ecomacrqaa001
        aksResourceGroup: ecom-rg-qa-canadacentral
        aksCluster: ecom-aks-cluster-qa-001
        promoteImageTag: ${{ parameters.PROMOTE_IMAGE_TAG }}

# ==========================================
# STAGE 4: PROMOTE & DEPLOY TO UAT
# ==========================================
- stage: DeployUAT
  dependsOn: [] 
  condition: eq('${{ parameters.ENVIRONMENT }}', 'uat')
  jobs:
  - job: PromoteAndDeploy
    steps:
    - template: templates/promote-deploy.yml
      parameters:
        environment: uat
        sourceAcr: ecomacrqaa001
        targetAcr: ecomacruata001
        aksResourceGroup: ecom-rg-uat-canadacentral
        aksCluster: ecom-aks-cluster-uat-001
        promoteImageTag: ${{ parameters.PROMOTE_IMAGE_TAG }}

# ==========================================
# STAGE 5: PROD APPROVAL
# ==========================================
- stage: ApproveProd
  dependsOn: []
  condition: eq('${{ parameters.ENVIRONMENT }}', 'prod')
  jobs:
  - job: ManualApproval
    pool: server
    steps:
    - task: ManualValidation@0
      inputs:
        notifyUsers: ''
        instructions: 'Approve to Push $(serviceName) image to PROD ACR and Deploy to AKS PROD cluster'
        onTimeout: 'reject'

# ==========================================
# STAGE 6: PROMOTE & DEPLOY TO PROD
# ==========================================
- stage: DeployProd
  dependsOn: ApproveProd
  condition: eq('${{ parameters.ENVIRONMENT }}', 'prod')
  jobs:
  - job: PromoteAndDeployProd
    steps:
    - template: templates/promote-deploy.yml
      parameters:
        environment: prod
        sourceAcr: ecomacruata001
        targetAcr: ecomacrproda001
        aksResourceGroup: ecom-rg-prod-canadacentral
        aksCluster: ecom-aks-cluster-prod-001
        promoteImageTag: ${{ parameters.PROMOTE_IMAGE_TAG }}

